### ISSUE TITLE
Search?

### ISSUE THREAD

**Issue by jregan2018** [practical-solutions/kkh-template#1]
I did not find anyway to conduct a simple search with template.

**Comment by practical-solutions** [comment]
This is correct, because I am using my SearchForm II-Plugin (beta-version, alternative: the original search form plugin, both can't be used at the same time) to place search bars individually. You are right that it should be possible to place the standard search field in the top right corner optionally. **I will add this option shortly.**

![grafik](https://user-images.githubusercontent.com/60605145/99874635-e720e880-2be9-11eb-93c7-59010fcd9e11.png)
