### ISSUE TITLE
Mobile layout issue

### ISSUE THREAD

**Issue by Monklite** [practical-solutions/kkh-template#3]
When on mobile (or reduced width in general), the "switch to content" href can be partially seen in the upper left hand corner. Since this is not visible in a regular orientation such as 16:9, I'm assuming this is not intentional and is supposed to be hidden.

**Comment by practical-solutions** [comment]
This is not intended. I must admit, I haven't optimized this template for mobile devices because I use it only on computers. I have added this issue to my development board but on secondary priority. I will leave this issue opened until it is solved. Probably there are more issues concerning the mobile layout. I would indeed welcome any PR.

**Comment by Monklite** [comment]
I'll see what I can do, can't promise anything though. Thanks!

**Comment by practical-solutions** [comment]
Thanks for the PR. It is merged.
